const districts = {
  Araria: "Araria",
  Aurangabad: "Aurangabad",
  Arwal: "Arwal",
  Banka: "Banka",
  Begusarai: "Begusarai",
  Bhagalpur: "Bhagalpur",
  Bhojpur: "Bhojpur",
  Buxar: "Buxar",
  Darbhanga: "Darbhanga",
  Gaya: "Gaya",
  Gopalganj: "Gopalganj",
  Jamui: "Jamui",
  Jehanabad: "Jehanabad",
  Kaimur: "Kaimur",
  Katihar: "Katihar",
  Khagaria: "Khagaria",
  Kishanganj: "Kishanganj",
  Lakhisarai: "Lakhisarai",
  Madhepura: "Madhepura",
  Madhubani: "Madhubani",
  Munger: "Munger",
  Muzaffarpur: "Muzaffarpur",
  Nalanda: "Nalanda",
  Nawada: "Nawada",
  PashchimChamparan: "PashchimChamparan",
  Patna: "Patna",
  PurbiChamparan: "PurbiChamparan",
  Purnia: "Purnia",
  Rohtas: "Rohtas",
  Saharsa: "Saharsa",
  Samastipur: "Samastipur",
  Saran: "Saran",
  Sheikhpura: "Sheikhpura",
  Sheohar: "Sheohar",
  Sitamarhi: "Sitamarhi",
  Siwan: "Siwan",
  Supaul: "Supaul",
  Vaishali: "Vaishali",
};

// Auto-generated block-to-district mapping from block.txt

const District_To_block = {
  Araria: [
    "Araria",
    "Bhargama",
    "Dahra",
    "Falka",
    "Forbesganj",
    "Jokihat",
    "Kursakanta",
    "Narpatganj",
    "Palasi",
    "Raniganj",
    "Sikty",
  ],
  Arwal: ["Arwal", "Kaler", "Kapri", "Kurtha", "Sonbhadra-Bansi-Surajpur"],
  Aurangabad: [
    "Aurangabad",
    "Barun",
    "Daudnagar",
    "Deo",
    "Goh",
    "Haspura",
    "Kutumba",
    "Madanpur",
    "Nabinagar",
    "Obra",
    "Rafiganj",
  ],
  Banka: [
    "Amarpur",
    "Banka",
    "Barahat",
    "Bausi",
    "Belhar",
    "Chandan",
    "Dhuraiya",
    "Fullidumar",
    "Katoria",
    "Rajaun",
    "Shambhuganj",
  ],
  Begusarai: [
    "Bachhwara",
    "Bakhri",
    "Ballia",
    "Barauni",
    "Begusarai",
    "Bhagwanpur",
    "Birpur",
    "Cheria Bariarpur",
    "Chhaurahi",
    "Dandari",
    "Gadhpura",
    "Khodawandpur",
    "Mansurchak",
    "Matihani",
    "Nawkothi",
    "Sahebpur Kamal",
    "Samho Akha Kurha",
    "Teghra",
  ],
  Bhagalpur: [
    "Bihpur",
    "Gopalpur",
    "Goradih",
    "Ismailpur",
    "Jagdishpur",
    "Kahalgaon",
    "Kharik",
    "Narayanpur",
    "Nathnagar",
    "Naugachhia",
    "Pirpainti",
    "Rangrachowk",
    "Sabour",
    "Shahkund",
    "Sonhaula",
    "Sultanganj",
  ],
  Bhojpur: [
    "Agiaon",
    "Ara",
    "Barhara",
    "Behea",
    "Charpokhari",
    "Garhani",
    "Jagdishpur",
    "Koilwar",
    "Piro",
    "Sahar",
    "Sandesh",
    "Shahpur",
    "Tarari",
    "Udwantnagar",
  ],
  Buxar: [
    "Brahmpur",
    "Buxar",
    "Chakki",
    "Chausa",
    "Chougain",
    "Dumraon",
    "Itarhi",
    "Kesath",
    "Nawanagar",
    "Rajpur",
    "Simri",
  ],
  Darbhanga: [
    "Alinagar",
    "Bahadurpur",
    "Baheri",
    "Benipur",
    "Biraul",
    "Darbhanga",
    "Gaurabauram",
    "Ghanshyampur",
    "Hanuman Nagar",
    "Hayaghat",
    "Jale",
    "Keotirunway",
    "Kiratpur",
    "Kusheshwar Asthan",
    "Kusheswar Asthan East",
    "Manigachhi",
    "Singhwara",
    "Tardih",
  ],
  Gaya: [
    "Amas",
    "Atri",
    "Bankey Bazar",
    "Barachatti",
    "Belaganj",
    "Bodhgaya",
    "Dobhi",
    "Dumaria",
    "Fatehpur",
    "Gaya Town",
    "Guraru",
    "Gurua",
    "Imamganj",
    "Khizarsarai",
    "Konch",
    "Manpur",
    "Mohanpur",
    "Mohra",
    "Neemchak Bathani",
    "Paraiya",
    "Sherghatty",
    "Tankuppa",
    "Tekari",
    "Wazirganj",
  ],
  Gopalganj: [
    "Baikunthpur",
    "Barauli",
    "Bhorey",
    "Bijaipur",
    "Gopalganj",
    "Hathua",
    "Kataiya",
    "Kuchaikote",
    "Manjha",
    "Panchdeori",
    "Phulwariya",
    "Sidhwaliya",
    "Thawe",
    "Uchkagaon",
  ],
  Jamui: [
    "Barhat",
    "Chakai",
    "Gidhor",
    "Islamnagar Aliganj",
    "Jamui",
    "Jhajha",
    "Khaira",
    "Laxmipur",
    "Sikandra",
    "Sono",
  ],
  Jehanabad: [
    "Ghoshi",
    "Hulasganj",
    "Jehanabad",
    "Kako",
    "Makhdumpur",
    "Modanganj",
    "Ratni Faridpur",
  ],
  Kaimur: [
    "Adhaura",
    "Bhabua",
    "Bhagwanpur",
    "Chainpur",
    "Chand",
    "Durgawati",
    "Kudra",
    "Mohania",
    "Nuaon",
    "Ramgarh",
    "Rampur",
  ],
  Katihar: [
    "Amdabad",
    "Azamnagar",
    "Balrampur",
    "Barari",
    "Barsoi",
    "Dandkhora",
    "Falka",
    "Hasanganj",
    "Kadwa",
    "Katihar",
    "Korha",
    "Kursela",
    "Manihari",
    "Mansahi",
    "Pranpur",
    "Sameli",
  ],
  Khagaria: [
    "Alauli",
    "Beldaur",
    "Chautham",
    "Gogri",
    "Khagaria",
    "Mansi",
    "Parbatta",
  ],
  Kishanganj: [
    "Bahadurganj",
    "Dighalbank",
    "Kishanganj",
    "Kochadhaman",
    "Pothia",
    "Terhagachh",
    "Thakurganj",
  ],
  Lakhisarai: [
    "Barahiya",
    "Channan",
    "Halsi",
    "Lakhisarai",
    "Pipariya",
    "Ramgarh Chowk",
    "Surajgarha",
  ],
  Madhepura: [
    "Alamnagar",
    "Bihariganj",
    "Chausa",
    "Gamhariya",
    "Ghelarh",
    "Gwalpara",
    "Kumarkhand",
    "Madhepura",
    "Murliganj",
    "Purani",
    "Shankarpur",
    "Singheshwar",
    "Udakishunganj",
  ],
  Madhubani: [
    "Andhratharhi",
    "Babu Barhi",
    "Basopatti",
    "Benipatti",
    "Bisfi",
    "Ghoghardiha",
    "Harlakhi",
    "Jainagar",
    "Jhanjharpur",
    "Kaluahi",
    "Khajauli",
    "Ladania",
    "Lakhnaur",
    "Laukaha (Khutauna)",
    "Laukahi",
    "Madhepur",
    "Madhwapur",
    "Pandaul",
    "Phulparas",
    "Rahika",
    "Rajnagar",
  ],

  Munger: [
    "Asarganj",
    "Bariyarpur",
    "Dharhara",
    "Jamalpur",
    "Kharagpur",
    "Munger Sadar",
    "Sangrampur",
    "Tarapur",
    "Tetiabambar",
  ],
  Muzaffarpur: [
    "Aurai",
    "Bandra",
    "Bochahan",
    "Gaighat",
    "Kanti",
    "Katra",
    "Kurhani",
    "Marwan",
    "Minapur",
    "Motipur",
    "Muraul",
    "Mushahari",
    "Paroo",
    "Sahebganj",
    "Sakra",
    "Saraiya",
  ],
  Nalanda: [
    "Asthawan",
    "Ben",
    "Biharsharif",
    "Bind",
    "Chandi",
    "Ekangarsarai",
    "Giriak",
    "Harnaut",
    "Hilsa",
    "Islampur",
    "Karai Parsurai",
    "Katrisarai",
    "Nagar Nausa",
    "Noorsarai",
    "Parbalpur",
    "Rahui",
    "Rajgir",
    "Sarmera",
    "Silao",
    "Tharthari",
  ],
  Nawada: [
    "Akbarpur",
    "Gobindpur",
    "Hisua",
    "Kashichak",
    "Kawakole",
    "Mescaur",
    "Nardiganj",
    "Narhat",
    "Nawada",
    "Pakri Barawan",
    "Rajauli",
    "Roh",
    "Sirdala",
    "Warisaliganj",
  ],
  PashchimChamparan: [
    "Bagaha",
    "Bettiah",
    "Bairia",
    "Bettiah",
    "Bhitaha",
    "Chanpatia",
    "Gaunaha",
    "Jogapatti",
    "Lauriya",
    "Madhubani",
    "Mainatand",
    "Majhaulia",
    "Narkatiaganj",
    "Nautan",
    "Piprasi",
    "Ramnagar",
    "Sikta",
    "Thakrahan",
  ],
  Patna: [
    "Athamalgola",
    "Bakhtiarpur",
    "Barh",
    "Belchchi",
    "Bihta",
    "Bikram",
    "Daniyawan",
    "Dhanarua",
    "Dinapur",
    "Dulhin Bazar",
    "Fatuha",
    "Ghoswari",
    "Khusrupur",
    "Maner",
    "Masaurhi",
    "Mokama",
    "Naubatpur",
    "Paliganj",
    "Pandarak",
    "Patna Sadar",
    "Phulwari",
    "Punpun",
    "Sampatchak",
  ],
  PurbiChamparan: [
    "Adapur",
    "Areraj",
    "Banjariya",
    "Bankatwa",
    "Chakia (Pipra)",
    "Chawradano",
    "Chiraiya",
    "Dhaka",
    "Ghorasahan",
    "Harsidhi",
    "Kalyanpur",
    "Kesaria",
    "Kotwa",
    "Madhuban",
    "Mehsi",
    "Motihari",
    "Paharpur",
    "Pakridayal",
    "Patahi",
    "Phenhara",
    "Pipra Kothi",
    "Ramgarhwa",
    "Raxaul",
    "Sangrampur",
    "Sugauli",
    "Tetariya",
    "Turkaulia",
  ],
  Purnia: [
    "Amour",
    "Baisa",
    "Baisi",
    "Banmankhi",
    "Barhara",
    "Bhawanipur",
    "Dagraua",
    "Dhamdaha",
    "Jalalgarh",
    "Kasba",
    "Krityanand Nagar",
    "Purnia East",
    "Rupouli",
    "Srinagar",
  ],
  Rohtas: [
    "Akorhigola",
    "Bikramganj",
    "Chenari",
    "Dawath",
    "Dehri",
    "Dinara",
    "Karakat",
    "Kargahar",
    "Kochas",
    "Nasriganj",
    "Nawhatta",
    "Nokha",
    "Rajpur",
    "Rohtas",
    "Sanjhouli",
    "Sasaram",
    "Sheosagar",
    "Surajpura",
    "Tilouthu",
  ],
  Saharsa: [
    "Banma Itahari",
    "Kahara",
    "Mahishi",
    "Nauhatta",
    "Patarghat",
    "Salkhua",
    "Sattar Kattaiya",
    "Simri Bakhtiarpur",
    "Sonbarsa",
    "Sour Bazar",
  ],
  Samastipur: [
    "Bibhutpur",
    "Bithan",
    "Dalsinghsarai",
    "Hasanpur",
    "Kalyanpur",
    "Khanpur",
    "Mohanpur",
    "Mohiuddinagar",
    "Morwa",
    "Patori",
    "Pusa",
    "Rosera",
    "Samastipur",
    "Sarairanjan",
    "Shivaji Nagar",
    "Singhia",
    "Tajpur",
    "Ujiarpur",
    "Vidyapati Nagar",
    "Warisnagar",
  ],
  Saran: [
    "Amnour",
    "Baniapur",
    "Chhapra",
    "Dariapur",
    "Dighwara",
    "Ekma",
    "Garkha",
    "Isuapur",
    "Jalalpur",
    "Lahladpur",
    "Maker",
    "Manjhi",
    "Marhaurah",
    "Mashrakh",
    "Nagra",
    "Panapur",
    "Parsa",
    "Revelganj",
    "Sonepur",
    "Taraiya",
  ],
  Sheikhpura: [
    "Ariari",
    "Barbigha",
    "Chewara",
    "Ghatkusumbha",
    "Sheikhpura",
    "Shekhopur Sarai",
  ],
  Sheohar: ["Dumari Katsari", "Piprahi", "Purnahiya", "Sheohar", "Tariyani"],
  Sitamarhi: [
    "Bairgania",
    "Bajpatti",
    "Bathanaha",
    "Belsand",
    "Bokhra",
    "Choraut",
    "Dumra",
    "Majorganj",
    "Nanpur",
    "Parihar",
    "Parsauni",
    "Pupri",
    "Riga",
    "Runnisaidpur",
    "Sonbarsa",
    "Suppi",
    "Sursand",
  ],
  Siwan: [
    "Andar",
    "Barharia",
    "Basantpur",
    "Bhagwanpur Hat",
    "Darauli",
    "Daraundha",
    "Goriakothi",
    "Hariah",
    "Hussainabad",
    "Maharajganj",
    "Mairwa",
    "Maharajganj",
    "Nagra",
    "Raghunathpur",
    "Siwan",
  ],
  Supaul: [
    "Bihpur",
    "Chhatapur",
    "Kishanpur",
    "Nirmali",
    "Pratapganj",
    "Supaul",
    "Tribeniganj",
  ],
  Vaishali: [
    "Auraiya",
    "Bihar",
    "Bidupur",
    "Desri",
    "Hajipur",
    "Mahnar",
    "Maharajganj",
    "Rajapakar",
    "Raja Pakar",
    "Sadar",
    "Saraiya",
    "Sursand",
  ],

  Sitamarhi: [
    "Bairgania",
    "Bajpatti",
    "Bathanaha",
    "Belsand",
    "Bokhra",
    "Choraut",
    "Dumra",
    "Majorganj",
    "Nanpur",
    "Parihar",
    "Parsauni",
    "Pupri",
    "Riga",
    "Runnisaidpur",
    "Sonbarsa",
    "Suppi",
    "Sursand",
  ],
  Sheikhpura: [
    "Ariari",
    "Barbigha",
    "Chewara",
    "Ghatkusumbha",
    "Sheikhpura",
    "Shekhopur Sarai",
  ],
  Sheohar: ["Dumari Katsari", "Piprahi", "Purnahiya", "Sheohar", "Tariyani"],
  Sitamarhi: [
    "Bairgania",
    "Bajpatti",
    "Bathanaha",
    "Belsand",
    "Bokhra",
    "Choraut",
    "Dumra",
    "Majorganj",
    "Nanpur",
    "Parihar",
    "Parsauni",
    "Pupri",
    "Riga",
    "Runnisaidpur",
    "Sonbarsa",
    "Suppi",
    "Sursand",
  ],
  Siwan: [
    "Andar",
    "Barharia",
    "Basantpur",
    "Bhagwanpur Hat",
    "Darauli",
    "Goriakothi",
    "Hariah",
    "Hussainabad",
    "Maharajganj",
    "Mairwa",
    "Maharajganj",
    "Nagra",
    "Raghunathpur",
    "Siwan",
  ],
  Supaul: [
    "Bihpur",
    "Chhatapur",
    "Kishanpur",
    "Nirmali",
    "Pratapganj",
    "Supaul",
    "Tribeniganj",
  ],
  Vaishali: [
    "Auraiya",
    "Bihar",
    "Bidupur",
    "Desri",
    "Hajipur",
    "Mahnar",
    "Maharajganj",
    "Rajapakar",
    "Raja Pakar",
    "Sadar",
    "Saraiya",
    "Sursand",
  ],
};
